name: build and publish docker image to dockerhub

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  run-tests:
    uses: nidhaloff/deep-translator-api/.github/workflows/test.yml@main

  build-push-docker:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nidhaloff/deep-translator-api:${{ steps.get_version.outputs.VERSION }}
