name: publish-docker

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: nidhaloff/deep-translator-api/.github/workflows/test.yml@main

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: docker login
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag nidhaloff/deep-translator-api:${{ steps.get_version.outputs.VERSION }}


      - name: Check docker images
        run: docker images


      - name: Docker Push
        run: docker push nidhaloff/${{github.repository}}
